[package]
name = "nur"
version = "0.1.0"
edition = "2021"
authors = [ "George Pollard <porges@porg.es>" ]

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
miette = { version = "4.7.1", features = ["fancy-no-backtrace"] }
nu-command = { version = "0.62.0", optional = true }
nu-engine = { version = "0.62.0", optional = true }
nu-parser = { version = "0.62.0", optional = true }
nur-lib = { path="../lib" }
serde_yaml = "0.8.24"
tokio = { version = "1.18.2", features = ["rt", "macros"] }

[features]
default = []
nu = ["dep:nu-command","dep:nu-engine","dep:nu-parser"]
