name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test --release --target x86_64-unknown-linux-musl --locked --verbose
      - run: cargo build --release --target x86_64-unknown-linux-musl --locked --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: nur
          path: target/x86_64-unknown-linux-musl/release/nur
          if-no-files-found: error
