name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install specific Rust version
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.71"
          target: x86_64-unknown-linux-musl
          components: clippy, rustfmt, llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: .devcontainer/install.sh
      - run: cargo llvm-cov nextest --all-targets --locked --workspace --lcov
      - run: cargo build --release --locked
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: nur
          path: target/x86_64-unknown-linux-musl/release/nur
          if-no-files-found: error
